In [ ]:
from turtledemo.chaos import line

import pandas as pd
from matplotlib.pyplot import figure

data = {
    "Name": ["Amaan", "Rahul", "Sakshi"],
    "Age": [20, 22, 23]
}

# data frame
df = pd.DataFrame(data)
# print(df)

# df

In [ ]:
# series properties

# 1. homogeneous
s = pd.Series([1, 2, 3, 4, "Amaan"], index=["a", "b", "c", "d", "name"])
# print(s)
# print(s["c"])
# print(s.index)

# 2. vectorized operations
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

In [ ]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)

s[5] = 55
print(s)

In [ ]:
# DataFrame

info = {
    "Name": ["Amaan", "Rahul", "Sakshi"],
    "Age": [20, 22, 23],
    "Gpa": [6.29, 7.21, 8.22]
}

df = pd.DataFrame(info)

print(df)

print(type(df))

print(df.index)

print(df.columns)
df

In [ ]:
info = pd.DataFrame([["Amaan", 21], ["atul", 24], ["ram", 26]], columns=["Name", "Age"])
print(info)

print(type(info))

info

In [ ]:
# csv operations

df = pd.read_csv("sample_students_data.csv")

df

In [ ]:
# methods
# df.head(3)
#
# df.tail(2)
#
# df.sample(3)
#
# df.info()

# df.shape

# df.describe()
#
# df.columns

df.nunique()

In [ ]:
# AQI DATASET

df = pd.read_csv("globalAirQuality.csv")

# df.head()
#
# df.tail()
#
# df.sample()
#
# df.info()
#
# df.shape


# df.columns

# df.nunique()

df.describe()

df

In [ ]:
# df[["country", "city"]]

# df.loc[0, "aqi"]

# df.loc[0:0, ["aqi", "country"]]

# df.iloc[0:2, [0, 1]]

# df.at[0, "city"]

# original data prevent to change using .copy()
cities = df["city"].copy()
cities[0] = "New York"

cities

In [ ]:
# filtering data

filteredData = df[df["aqi"] > 144][["city", "aqi"]]

# filteredData
# filteredData.iloc[0]
filteredData.loc[3]

In [ ]:
df = pd.read_csv("raw_data.csv")

df

In [ ]:
df.isnull()
df.isna()

df.isnull().sum()

df.dropna()
df.dropna(axis=1)

missing_values = {
    'name': 'Amaan',
    'age': 22,
    'country': 'India',
    'gender': 'Male',
    'income': df['income'].mean()
}

df.fillna(missing_values).copy()

df.ffill()

df.bfill()

In [ ]:
# Handle-Duplicates

df[['name', 'gender']].duplicated()
df['income'].duplicated()

df.duplicated()
df2 = df.copy()  # copy of original dataFrame
df.drop_duplicates()

In [ ]:
# handle data types


# df['age'] = df['age'].fillna(0).astype(int)
df.dtypes
# df['age']

In [ ]:
df

In [ ]:
df = pd.read_csv('globalAirQuality.csv')

df

In [ ]:
# date-time

df['timestamp'] = pd.to_datetime(df['timestamp'])

df['timestamp'].dtypes

In [ ]:
# handling strings

df = pd.read_csv("raw_data.csv")

df

In [ ]:
# String methods
df['name'].str.lower()
df['name'].str.upper()
df['name'].str.capitalize()
df['country'].str.title()

df['name'].str.split(" ")

df['country'].str.contains("US")
df['country'].str.contains('india', case=False)  # just checks value without any case sensitivity

In [ ]:
df = pd.read_csv("raw_data.csv")

df2 = df.copy()

# map method
df2['gender'] = df2['gender'].map({'Male': 'M', 'Female': 'F', 'Unknown': 'U'})

# assign method
df2.assign(new_income=df2['income'] * 1.1)

# replace method
df2["country"] = df2["country"].replace('USA', 'United States of America')

df2["country"]

In [ ]:
# df2['tax'] = df2['income'].apply(lambda x: "20%" if x >= 50000 else "10%")

df2 = df2.rename(columns={"income": "salary"})

sorted_df = df2.sort_values('salary')

df2 = sorted_df.sort_index()

df2['ranking'] = sorted_df['salary'].rank(ascending=False, method='dense')

df2
#
# df2 = sorted_df
#

In [ ]:
# Practice Task

df = pd.read_csv("raw_data.csv")

df2 = df.copy()

# list comprehension Examples
# squares = []
#
# for i in range(1, 6):
#     squares.append(i * i)
#
# print(squares)


# squares = [i * i for i in range(1, 6)]
#
# squares

# Applying list comprehension
cols = [col for col in df2.columns if col != 'id'] + ['id']

df2[cols]

In [ ]:
df2 = df.copy()

df2 = df2.sort_values('income')

df2 = df2.drop_duplicates()

df2 = df2.fillna(0)

df2 = df2.reset_index()

df2.to_csv('sorted_data.csv')  # writing in csv file

df2.to_json('sorted_data.json')  # writing data in JSON file

In [ ]:
# grouping and aggregation of data

# groupby()
df2.groupby('gender')['id'].count()

df2.groupby('gender')['income'].max()

df2.groupby('country')['income'].mean()

# agg()
df2.groupby('country')['income'].agg(['mean', 'min', 'max'])

df2.groupby('country').agg({
    'income': 'mean',
    'age': 'mean'
})

In [ ]:
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

melted_df = df.melt(
    id_vars=["country", "year"],
    value_vars=['sales', 'profit'],
    var_name='matrics',
    value_name='value'
)

melted_df.pivot(
    index=['country', 'year'],
    columns='matrics',
    values='value'
)

In [ ]:
df = pd.read_csv('employee_data.csv')

df['Age'].hist(bins=5, figsize=(6, 4), color="skyblue", edgecolor="black")

df.plot(kind='scatter',x = 'Age', y = 'Salary', title="Salary Trend")

In [ ]:
# Merging & Joining
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

pd.merge(df_customers, df_orders, on="customer_id")                  # Inner Join
pd.merge(df_customers, df_orders, on="customer_id", how="left")      # Left Join
pd.merge(df_customers, df_orders, on="customer_id", how="right")     # Right Join
pd.merge(df_customers, df_orders, on="customer_id", how="outer")     # Outer Join

In [34]:
# Concatenation
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["David", "Eva", "Frank"]
})

In [39]:
pd.concat([df1, df2])
pd.concat([df1, df2],ignore_index=True)
pd.concat([df1, df2],axis=1)

   id     name  id   name
0   1     Adam   4  David
1   2      Bob   5    Eva
2   3  Charlie   6  Frank

In [31]:
df1

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie

In [32]:
df2

   id   name
0   4  David
1   5    Eva
2   6  Frank